modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="siege_machine_compat"
version="${version}"
displayName="Recruits Siege Compatibility"
authors="Knightmare,Magistu"
description='''
Adds AI compatibility between Recruits and Magistu's Medieval Siege Machines.
Recruits bowmen can operate ranged siege weapons.
Recruits melee and shieldmen can operate battering rams and siege ladders.
'''
[[dependencies.siege_machine_compat]]
modId = "minecraft"
versionRange = "[1.20.1,1.21)"
mandatory = true
side = "BOTH"
ordering = "NONE"

[[dependencies.siege_machine_compat]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.siege_machine_compat]]
modId="recruits"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.siege_machine_compat]]
modId="siegemachines"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
